import type { Destination, Testimonial, BookingAddon, Experience } from "./types"

export const destinations: Destination[] = [
  {
    id: "santorini-villa",
    title: "Santorini Private Villa",
    location: "Greece",
    description:
      "Experience the breathtaking views of the Aegean Sea from your private infinity pool villa perched on the cliffs of Santorini. This exclusive property features 4 bedrooms, a personal chef, and daily housekeeping service.",
    price: 4500,
    priceUnit: "week",
    rating: 4.9,
    image: "/images/santorini.png",
    amenities: [
      "Private Pool",
      "Ocean View",
      "Personal Chef",
      "Concierge Service",
      "Airport Transfer",
      "Daily Cleaning",
    ],
    featured: true,
    category: "luxury",
  },
  {
    id: "maldives-suite",
    title: "Maldives Overwater Suite",
    location: "Maldives",
    description:
      "Indulge in ultimate luxury in this overwater villa with direct access to the crystal-clear waters of the Maldives. Enjoy a glass floor to observe marine life, private butler service, and exclusive spa treatments.",
    price: 6200,
    priceUnit: "week",
    rating: 4.8,
    image: "/images/maldives.png",
    amenities: [
      "Overwater Villa",
      "Private Butler",
      "Glass Floor",
      "Spa Access",
      "Snorkeling Equipment",
      "Sunset Cruise",
    ],
    featured: true,
    category: "luxury",
  },
  {
    id: "swiss-chalet",
    title: "Alpine Luxury Chalet",
    location: "Switzerland",
    description:
      "Nestled in the Swiss Alps, this luxury chalet offers ski-in/ski-out access, a private hot tub, and breathtaking mountain views. Perfect for winter sports enthusiasts or summer hiking adventures.",
    price: 5800,
    priceUnit: "week",
    rating: 4.7,
    image: "/images/swiss-alps.png",
    amenities: ["Ski-in/Ski-out", "Hot Tub", "Fireplace", "Mountain View", "Sauna", "Chef Service"],
    featured: true,
    category: "adventure",
  },
  {
    id: "kyoto-ryokan",
    title: "Traditional Kyoto Ryokan",
    location: "Japan",
    description:
      "Experience authentic Japanese hospitality in this exclusive ryokan. Featuring traditional tatami rooms, private onsen baths, and kaiseki dining prepared by master chefs.",
    price: 850,
    priceUnit: "night",
    rating: 4.9,
    image: "/images/kyoto.png",
    amenities: [
      "Private Onsen",
      "Kaiseki Dining",
      "Tea Ceremony",
      "Garden View",
      "Kimono Experience",
      "Cultural Tours",
    ],
    featured: false,
    category: "cultural",
  },
  {
    id: "amalfi-villa",
    title: "Amalfi Coast Villa",
    location: "Italy",
    description:
      "Perched on the cliffs of the Amalfi Coast, this historic villa offers panoramic views of the Mediterranean, a private garden with citrus trees, and easy access to charming coastal towns.",
    price: 5200,
    priceUnit: "week",
    rating: 4.8,
    image: "/images/amalfi.png",
    amenities: ["Sea View", "Private Garden", "Historic Property", "Wine Cellar", "Boat Access", "Chef Service"],
    featured: false,
    category: "luxury",
  },
  {
    id: "bali-retreat",
    title: "Bali Wellness Retreat",
    location: "Indonesia",
    description:
      "Rejuvenate your mind and body at this exclusive wellness retreat in Ubud. Featuring daily yoga sessions, organic cuisine, spa treatments, and meditation pavilions surrounded by lush rice terraces.",
    price: 3800,
    priceUnit: "week",
    rating: 4.7,
    image: "/images/bali.png",
    amenities: [
      "Yoga Pavilion",
      "Spa Treatments",
      "Organic Meals",
      "Meditation Spaces",
      "Private Pool",
      "Wellness Workshops",
    ],
    featured: true,
    category: "wellness",
  },
]

export const experiences: Experience[] = [
  {
    id: "historical-castle-stays",
    title: "Historical Castle Stays",
    location: "Europe",
    description:
      "Step back in time with exclusive access to historic castles and palaces converted into luxury accommodations. Experience the grandeur of European nobility with modern comforts.",
    price: 3200,
    priceUnit: "week",
    rating: 4.9,
    image: "/images/historical-castle.png",
    category: "luxury",
    featured: true,
  },
  {
    id: "michelin-culinary-journeys",
    title: "Michelin-Star Culinary Journeys",
    location: "Worldwide",
    description:
      "Embark on a gastronomic adventure featuring private dining experiences at the world's most acclaimed restaurants, cooking classes with renowned chefs, and exclusive wine tastings.",
    price: 4500,
    priceUnit: "week",
    rating: 4.8,
    image: "/images/culinary-journey.png",
    category: "culinary",
    featured: true,
  },
  {
    id: "private-vineyard-tours",
    title: "Private Vineyard Tours",
    location: "Wine Regions",
    description:
      "Discover the world's most prestigious wine regions with private tours of exclusive vineyards, tastings of rare vintages, and accommodations at luxury wine estates.",
    price: 3800,
    priceUnit: "week",
    rating: 4.7,
    image: "/images/vineyard-tour.png",
    category: "culinary",
    featured: true,
  },
  {
    id: "private-yacht-charters",
    title: "Private Yacht Charters",
    location: "Mediterranean & Caribbean",
    description:
      "Set sail on a luxury yacht with a professional crew, exploring hidden coves, pristine beaches, and exclusive ports of call at your own pace.",
    price: 15000,
    priceUnit: "week",
    rating: 4.9,
    image: "/images/yacht-charter.png",
    category: "adventure",
    featured: true,
  },
  {
    id: "cultural-capitals",
    title: "Cultural Capitals Immersion",
    location: "Asia & Europe",
    description:
      "Immerse yourself in the world's most fascinating cultural capitals with private guides, behind-the-scenes access to museums and historical sites, and authentic local experiences.",
    price: 4200,
    priceUnit: "week",
    rating: 4.8,
    image: "/images/cultural-capital.png",
    category: "cultural",
    featured: true,
  },
  {
    id: "bali-wellness",
    title: "Bali Wellness Journey",
    location: "Indonesia",
    description:
      "Transform mind, body, and spirit with our exclusive wellness journey in Bali. Enjoy private yoga sessions, traditional healing treatments, meditation retreats, and organic cuisine in luxurious villa accommodations.",
    price: 4800,
    priceUnit: "week",
    rating: 4.9,
    image: "/images/bali.png",
    category: "wellness",
    featured: true,
  },
]

export const testimonials: Testimonial[] = [
  {
    id: "test1",
    name: "Alexandra Reynolds",
    title: "Executive Traveler",
    avatar: "/images/avatar1.png",
    content:
      "The personalized service and exclusive access to luxury accommodations made our trip unforgettable. Worth every penny for the premium experience.",
    rating: 5,
  },
  {
    id: "test2",
    name: "Jonathan Chen",
    title: "Luxury Explorer",
    avatar: "/images/avatar2.png",
    content:
      "PrimeTravels arranged our honeymoon to the Maldives with impeccable attention to detail. The private butler service and sunset cruises were highlights of our stay.",
    rating: 5,
  },
  {
    id: "test3",
    name: "Sophia Martinez",
    title: "Frequent Traveler",
    avatar: "/images/avatar3.png",
    content:
      "Having a dedicated travel consultant made all the difference. They secured upgrades and special experiences that would have been impossible to arrange on my own.",
    rating: 4,
  },
]

export const popularDestinations = [
  { value: "santorini", label: "Santorini, Greece" },
  { value: "maldives", label: "Maldives" },
  { value: "swiss-alps", label: "Swiss Alps" },
  { value: "kyoto", label: "Kyoto, Japan" },
  { value: "amalfi", label: "Amalfi Coast, Italy" },
  { value: "bali", label: "Bali, Indonesia" },
  { value: "paris", label: "Paris, France" },
  { value: "new-york", label: "New York, USA" },
  { value: "dubai", label: "Dubai, UAE" },
  { value: "sydney", label: "Sydney, Australia" },
]

export const bookingAddons: BookingAddon[] = [
  {
    id: "private-transfer",
    name: "Private Airport Transfer",
    description: "Luxury vehicle with professional driver for seamless airport transfers",
    price: 150,
    category: "transfer",
    image: "/placeholder.svg?height=200&width=300&text=Private+Transfer",
  },
  {
    id: "helicopter-transfer",
    name: "Helicopter Transfer",
    description: "Scenic helicopter transfer from the airport to your accommodation",
    price: 1200,
    category: "transfer",
    image: "/placeholder.svg?height=200&width=300&text=Helicopter+Transfer",
  },
  {
    id: "private-chef",
    name: "Private Chef Experience",
    description: "Enjoy a customized gourmet meal prepared by a private chef in your accommodation",
    price: 350,
    category: "service",
    image: "/placeholder.svg?height=200&width=300&text=Private+Chef",
  },
  {
    id: "spa-package",
    name: "Premium Spa Package",
    description: "Comprehensive spa treatment package including massage, facial, and body treatments",
    price: 280,
    category: "service",
    image: "/placeholder.svg?height=200&width=300&text=Spa+Package",
  },
  {
    id: "guided-tour",
    name: "Private Guided Tour",
    description: "Exclusive guided tour of local attractions with an expert local guide",
    price: 220,
    category: "experience",
    image: "/placeholder.svg?height=200&width=300&text=Guided+Tour",
  },
  {
    id: "sunset-cruise",
    name: "Sunset Yacht Cruise",
    description: "Private yacht cruise with champagne and canapés at sunset",
    price: 450,
    category: "experience",
    image: "/placeholder.svg?height=200&width=300&text=Sunset+Cruise",
  },
  {
    id: "room-upgrade",
    name: "Room/Suite Upgrade",
    description: "Upgrade to the next room category or suite, subject to availability",
    price: 200,
    category: "upgrade",
    image: "/placeholder.svg?height=200&width=300&text=Room+Upgrade",
  },
  {
    id: "celebration-package",
    name: "Celebration Package",
    description: "Special celebration setup with champagne, flowers, and personalized cake",
    price: 180,
    category: "service",
    image: "/placeholder.svg?height=200&width=300&text=Celebration+Package",
  },
]
